cameras:
  Camera_1:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 2560
      Size_y: 1440
    Type: LIVE_STREAM
    enabled: true
    mark_points:
    - - 726
      - 924
    - - 1320
      - 924
    - - 1482
      - 974
    - - 1540
      - 1070
    - - 764
      - 1084
    - - 766
      - 1046
    - - 736
      - 1032
    person_limit: 5
    point_zoom: null
    record_video: true
    reverse_point:
    - 720
    - 440
    save_data: false
    save_ng: false
    save_ok: false
    source: rtsp://admin:Aoyama456@10.17.7.246:554/cam/realmonitor?channel=1&subtype=0
    start_point:
    - 1118
    - 1010
  Camera_2:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: Video
    enabled: false
    mark_points:
    - - 114
      - 518
    - - 481
      - 481
    - - 474
      - 622
    - - 146
      - 611
    person_limit: 5
    record_video: false
    reverse_point: null
    save_ng: false
    save_ok: false
    source: ../video_model/videoTrain2.mp4
    start_point: null
  Camera_3:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: LIVE_STREAM
    enabled: true
    mark_points:
    - - 1044
      - 756
    - - 1330
      - 762
    - - 1324
      - 904
    - - 968
      - 888
    person_limit: 5
    point_zoom:
    - 1248
    - 288
    record_video: true
    reverse_point:
    - 1118
    - 1412
    save_data: true
    save_ng: false
    save_ok: false
    source: rtsp://admin:aoyama123456@10.17.7.43:554/Streaming/Channels/101/
    start_point:
    - 1164
    - 812
  Camera_4:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: LIVE_STREAM
    enabled: false
    mark_points:
    - - 185
      - 409
    - - 367
      - 405
    - - 383
      - 476
    - - 194
      - 482
    - - 194
      - 461
    - - 180
      - 457
    person_limit: 5
    point_zoom: null
    record_video: false
    reverse_point:
    - 310
    - 628
    save_ng: false
    save_ok: false
    source: 0
    start_point:
    - 282
    - 448
  Camera_5:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: LIVE_STREAM
    enabled: true
    person_limit: 5
    record_video: true
    save_ng: false
    save_ok: false
    source: 1
  Camera_6:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: Video
    enabled: false
    mark_points:
    - - 560
      - 686
    - - 1145
      - 707
    - - 1193
      - 807
    - - 582
      - 814
    - - 582
      - 790
    - - 553
      - 779
    person_limit: 5
    point_zoom: null
    record_video: false
    reverse_point:
    - 961
    - 1019
    save_data: true
    save_ng: false
    save_ok: false
    source: ../video_model/videoTrain3.mp4
    start_point:
    - 876
    - 765
  Camera_8:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: LIVE_STRAME
    enabled: false
    mark_points:
    - - 64
      - 124
    - - 126
      - 136
    - - 106
      - 227
    - - 56
      - 209
    point_zoom: null
    reverse_point:
    - 80
    - 290
    save_ng: false
    save_ok: false
    source: 0
    start_point:
    - 91
    - 168
  Camera_Test:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1980
      Size_y: 1080
    Type: Video
    enabled: false
    save_ng: false
    save_ok: false
    source: ../../ProjectDetection/recordings/VideoTrain_20260817_153543.mp4
global:
  active_model: model\pose_classifier_1 copy.pkl
  dataset_path: pose_dataset_label.csv
  default_camera_id: Camera_6
  default_person_limit: 3
  detection_confidence: 0.9
  model_type: full
  presence_confidence: 0.9
  record_height: 300
  record_width: 100
  tracking_confidence: 0.9
  video_path: video_model
model:
  Model_path_1:
    source: model\pose_classifier_18-08-2026-09-38-52_.pkl
  Model_path_2:
    source: model\pose_classifier_1.pkl
  Model_path_3:
    source: model\pose_classifier.pkl
  Model_path_4:
    source: model\pose_classifier_10_55-31-07-2026.pkl
  Model_path_5:
    source: model\pose_classifier_11_25-31-07-26.pkl
  Model_path_6:
    source: model\pose_classifier_13_15-31-7-26.pkl
