cameras:
  Camera_1:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: Video
    enabled: false
    person_limit: 5
    record_video: false
    save_ng: false
    save_ok: false
    source: video_model\videoTrain1.mp4
  Camera_2:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: Video
    enabled: false
    mark_points:
    - - 346
      - 913
    - - 701
      - 980
    - - 695
      - 1053
    - - 313
      - 983
    person_limit: 5
    record_video: false
    save_ng: false
    save_ok: false
    source: video_model\videoTrain2.mp4
  Camera_3:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: Video
    enabled: false
    mark_points:
    - - 369
      - 627
    - - 731
      - 621
    - - 773
      - 725
    - - 388
      - 725
    - - 392
      - 693
    - - 369
      - 687
    person_limit: 5
    record_video: false
    reverse_point:
    - 624
    - 945
    save_ng: false
    save_ok: true
    source: video_model\videoTrain3.mp4
    start_point:
    - 563
    - 681
  Camera_4:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: Video
    enabled: false
    mark_points:
    - - 367
      - 639
    - - 714
      - 639
    - - 768
      - 708
    - - 390
      - 718
    - - 389
      - 693
    - - 367
      - 688
    person_limit: 5
    record_video: false
    reverse_point:
    - 612
    - 953
    save_ng: false
    save_ok: false
    source: video_model\videoTrain4.mp4
    start_point:
    - 568
    - 677
  Camera_5:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: LIVE_STREAM
    enabled: true
    person_limit: 5
    record_video: true
    save_ng: false
    save_ok: false
    source: 0
  Camera_6:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: LIVE_STREAM
    enabled: true
    person_limit: 5
    record_video: true
    save_ng: false
    save_ok: false
    source: 1
  Camera_7:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: LIVE_STREAM
    enabled: true
    person_limit: 5
    record_video: false
    save_ng: false
    save_ok: false
    source: rtsp://admin:Aoyama456@xx.xx.xx.xx:xx/cam/realmonitor?channel=1&subtype=0
  Camera_8:
    Display:
      Position_x: 946
      Position_y: 486
      Size_x: 945
      Size_y: 485
    Type: LIVE_STREAM
    enabled: false
    person_limit: 5
    record_video: false
    source: rtsp://admin:aoyama123456@xx.xx.x.xx:xx/Streaming/Channels/101/
global:
  active_model: model\pose_classifier_1 copy.pkl
  dataset_path: ..\..\dataset\pose_dataset copy 2.csv
  default_person_limit: 3
  detection_confidence: 0.9
  model_type: full
  presence_confidence: 0.9
  record_height: 300
  record_width: 100
  tracking_confidence: 0.9
  video_path: video_model
model:
  Model_path_1:
    source: model\pose_classifier_1.pkl
  Model_path_2:
    source: model\pose_classifier_1.pkl
  Model_path_3:
    source: model\pose_classifier.pkl
