cameras:
  Camera_1:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: Video
    enabled: false
    person_limit: 5
    record_video: false
    save_ng: false
    save_ok: false
    source: ../video_model/videoTrain1.mp4
  Camera_2:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: Video
    enabled: false
    mark_points:
    - - 114
      - 518
    - - 481
      - 481
    - - 474
      - 622
    - - 146
      - 611
    person_limit: 5
    record_video: false
    reverse_point: null
    save_ng: false
    save_ok: false
    source: ../video_model/videoTrain2.mp4
    start_point: null
  Camera_3:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: Video
    enabled: false
    mark_points:
    - - 189
      - 407
    - - 363
      - 402
    - - 387
      - 482
    - - 200
      - 484
    - - 190
      - 459
    person_limit: 5
    point_zoom: null
    record_video: false
    reverse_point:
    - 308
    - 623
    save_ng: false
    save_ok: true
    source: ../video_model/videoTrain3.mp4
    start_point:
    - 281
    - 445
  Camera_4:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: Video
    enabled: false
    mark_points:
    - - 184
      - 411
    - - 367
      - 407
    - - 387
      - 478
    - - 192
      - 481
    - - 192
      - 463
    - - 180
      - 459
    person_limit: 5
    point_zoom: null
    record_video: false
    reverse_point:
    - 310
    - 628
    save_ng: false
    save_ok: false
    source: ../video_model/videoTrain4.mp4
    start_point:
    - 282
    - 448
  Camera_5:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: LIVE_STREAM
    enabled: true
    mark_points:
    - - 282
      - 264
    - - 348
      - 265
    - - 349
      - 323
    - - 266
      - 311
    person_limit: 5
    point_zoom:
    - 306
    - 217
    record_video: true
    reverse_point:
    - 278
    - 622
    save_ng: false
    save_ok: false
    source: rtsp://admin:aoyama123456@10.17.7.43:554/Streaming/Channels/101/
    start_point:
    - 309
    - 291
  Camera_6:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: LIVE_STREAM
    enabled: true
    person_limit: 5
    record_video: true
    save_ng: false
    save_ok: false
    source: 1
  Camera_7:
    Display:
      Position_x: 0
      Position_y: 0
      Size_x: 1920
      Size_y: 1080
    Type: LIVE_STREAM
    enabled: true
    mark_points:
    - - 182
      - 409
    - - 367
      - 403
    - - 387
      - 481
    - - 193
      - 486
    - - 194
      - 470
    - - 182
      - 460
    person_limit: 5
    point_zoom: null
    record_video: true
    reverse_point:
    - 310
    - 617
    save_ng: false
    save_ok: false
    source: rtsp://admin:Aoyama456@10.17.7.246:554/cam/realmonitor?channel=1&subtype=0
    start_point:
    - 279
    - 445
global:
  active_model: model\pose_classifier_1 copy.pkl
  dataset_path: ..\..\dataset\pose_dataset copy 2.csv
  default_person_limit: 3
  detection_confidence: 0.9
  model_type: full
  presence_confidence: 0.9
  record_height: 300
  record_width: 100
  tracking_confidence: 0.9
  video_path: video_model
model:
  Model_path_1:
    source: model\pose_classifier_1-08-26-10_24.pkl
  Model_path_2:
    source: model\pose_classifier_1.pkl
  Model_path_3:
    source: model\pose_classifier.pkl
  Model_path_4:
    source: model\pose_classifier_10_55-31-07-2026.pkl
  Model_path_5:
    source: model\pose_classifier_11_25-31-07-26.pkl
  Model_path_6:
    source: model\pose_classifier_13_15-31-7-26.pkl
